# Generated by Django 3.0.5 on 2020-12-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationModel',
            fields=[
                ('registration_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contact', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('otp', models.IntegerField()),
                ('doj', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=100)),
            ],
        ),
    ]
